export default {
    state: {
        intro: {h1: 'Hi', i1: '👋🏽', i2: '👩🏾‍💻👨🏽‍💻👨‍💻', h2: 'I\'m Ben', p1: 'A UI/UX Designer who focuses on crafting delightful digital experience for all users.', p2: 'Here are few of my works...'},
        project: { active: false, project: {}},
        projects: [
            { id: 1, color: '#566FF4', color2: '#566FF4', type: 'project', title: 'Flexsale', thumbnail: require('@/assets/images/flexsale.png'), banner: require('@/assets/images/flexsale-banner.png'), banner_2: '', description: 'A multi-platform point of sale and inventory management system.',
                overview: { problem: 'So many local retailers still uses physical books in keeping records of their stock.  This method is tedious, unreliable and overall inefficient.  Consumable products exceed their expiration dates without the owners knowledge, retail shop owner finds it impossible to accurately compute sale analysis on their stock, and theft are a few challenges that plummets the local retail industry.', product: 'Flexsale is a multi-platform application designed to uniquely help retail shops keep track of their inventory and perform everyday transaction with ease.', goal: 'Design a multi-platform application that will help retail shop owners to record their daily sales, keep track of their stock limits, get reminders on expiring products, and perform various sales analysis with ease.', role: 'UX designer designing the app for all screen sizes and devices.', responsibilities: 'Conducting user interviews, paper and digital wire-framing, low and high-fidelity prototyping, conducting usability studies, accounting for accessibility, and iterating on designs.', duration: 'September, 2021 - December, 2021'},
                empathize: { overview: 'In order to understand the users I’m designing for, I conducted a user research on 10 retail shops, and below are the insights drawn from the study;', pain_points: [ { id: 1, title: 'Mobile and accessibility', description: 'Most inventory management systems on the market are only desktop based and operates as a stand-alone application.', title2: 'Multi-platform app', opportunity: 'Design a multi-platform application that can be accessible from all devices.'}, { id: 2, title: 'Product expiration', description: 'Retails shop owners couldn’t keep track of the expiration dates of consumable products.', title2: 'Notification prompt', opportunity: 'Include an active notification prompt that will constantly alert shop owners about the expiration  status of all their consumables.' }, { id: 3, title: 'Connectivity problem ', description: 'Some retail shops are located in places with poor network connectivity.', title2: 'Offline accessible feature', opportunity: 'Include an offline accessibility feature to enable users to seamlessly perform basic features and saving them locally in other to be synced with the cloud whenever they come online.'} ], person_name: 'Mary', problem_statement: 'Mary is a grocery shop owner who needs keep track of her inventory status and also record her daily sales because she wants to know how which products are performing well within a specific period or time, know the quality of new products to order for,  and know if a product if getting near to expiration.', persona_img: require('@/assets/images/person-2.png'), age: '28', education: 'BSc Business Administration', hometown: 'Ho, Ghana', family: 'Married with 3 Children', ocupation: 'Entrepreneur', headline: '“It’s too exhausting doing everything manually in this day and age. I just need a system to automate all my tasks so that can free my time for other things“', goals: [{id: 1, data: 'A system to help me keep sales record, and keep track of my inventory.'}, {id: 2, data: 'I need to be able to access my inventory records and perform basic functions even when I’m offline.'}, {id: 3, data: 'I need to be reminded of when products are near expiration.'}], frustrations: [{id: 1, data: 'Most systems I’ve used in the past are ineffective because they are inaccessible remotely and aren’t mobile compatible.'},{id: 2, data: 'My products expires without my knowledge.'}], scenario: '', competitive_audit: '', audit_img: '', ideation: '', ideation_img: '', user_journey_map: '', user_journey_map_img: ''},
                starting_the_design: { site_map: '', site_map_img: '', paper_wireframe: '', paper_wireframe_img: '', digital_wireframe: '', digital_wireframe_img: '', screen_variations: '', screen_variations_imgs: [], lofi_prototyp: '', lofi_prototype_img: '', usability_study: '', usability_study_fidings: [] },
                refining_the_design: { before_after: [], accessibility_considerations: [], refined_designs: [], screen_variations: '', screen_variations_imgs: [], hifi_prototype: '', hifi_prototype_video: '', video_title: ''},
                going_forward: { takeaways: [], nextstep: []}
            },
            { id: 2, color: '#95B1ED', color2: '#3C74EB', type: 'case study', title: 'Infinity Movies', thumbnail: require('@/assets/images/sample.png'), banner: require('@/assets/images/project-2-banner.png'), banner_2: '', description: 'Movie trailer app for booking upcoming shows and streaming on-demand. ',
                overview: { problem: 'College students and busy workers needs to quickly book tickets for the movies.', product: 'Oculus Movie Theater is located in Accra, Ghana. They have a high capacity theater with ultra-modern equipments that delight users with superb viewing experience. Their target customers include working adults and college students who like to hang out during the weekends. Oculus Theater aims to become the preferred destination for movies lovers in and around the metropolis.', goal: 'Design an app for Oculus Theater to enable its users to watch movies trailers for upcoming movies and easily book their tickets.', role: 'UX designer, designing the app from conception to delivery.', responsibilities: 'Conducting user interviews, paper and digital wireframing, low and high-fidelity prototyping, conducting usability studies, accounting for accessibility, and iterating on designs.', duration: 'June, 2021 - August, 2021'},
                empathize: { overview: 'I conducted interviews and created empathy maps in order to understand the users I’m designing for and their needs. The primary user groups identified going into the research were college students and working adults. These user groups were confirmed during the research conducted on Oculus Theater customers. However, the research also revealed that not only do users want a quick and smooth platform to book ticket for the theater, but most working adults also prefers an in-app movie rentals.', pain_points: [{ id: 1, title: 'Accessibility', description: 'Most trailer apps do a poor job in considering users with special needs such as hearing impediment.', title2: 'Closed Caption', opportunity: 'Include a closed captioning feature for users with hearing problem.'}, { id: 2, title: 'Time', description: 'Most working adults and some students have limited time to keep up to date with theater schedules.', title2: 'In-app book', opportunity: 'Allow users to directly buy tickets from the app.'}, { id: 3, title: 'Flexibility', description: 'Movie trailer apps in the metropolis only provide users with one type of service only thus, either booking tickets or in-app streaming but not both.', title2: 'oooo', opportunity: 'Introduce an in-app streaming feature for users who cannot visit the theater.' } ], person_name: 'Tyler', problem_statement: 'Tyler is a full time student who needs a convenient way to book tickets for the movies from his dormitory room because he has limited time to do it in-person.', persona_img: require('@/assets/images/person-2.png'), age: '19', education: 'BSc. Mathematics', hometown: 'Accra, Ghana', family: 'Single, leaves alone', ocupation: 'student', headline: '"I need a place to watch good movies, but it will be nice if I could browse the trailers first before booking my ticket."', goals: [{id: 1, data: 'I need to watch latest movie trailers.'}, { id: 2, data: 'I prefer to watch especially action movies.'}, {id: 3, data: 'To watch movies in comfortable seats.'}], frustrations: [{id: 1, data: 'Movie trailer apps sometimes show old movies.'}, {id: 2, data: 'Trailer buffers and take way too long to play.'}, {id: 3, data: 'The theater seats are terrible, it is frustrating.'}], scenario: 'Tyler is a level 400 student studying Mathematics at the University of Ghana. He likes to take his head off studying on Friday night and enjoy some movies at the theater. He usually browses through movie trailers and book his seat at the directly from the app. Tyler gets frustrated whenever the app pops displays old movies. Tyler wants to see latest action movie trailers. He also prefers attend the theater on Fridays.', competitive_audit: '', audit_img: '', ideation: '', ideation_img: '', user_journey_map: '', user_journey_map_img: ''},
                starting_the_design: { site_map: '', site_map_img: '', paper_wireframe: 'I created paper wireframes first because it’s easier to quickly ideate through and gather all my thoughts before moving to digital wire-frames.', paper_wireframe_img: require('@/assets/images/paper_wireframe_1.png'), digital_wireframe: 'The paper wire-frames were converted in to digital wire-frames with some few modifications.', digital_wireframe_img: require('@/assets/images/digital_wireframe.png'), screen_variations: '', screen_variations_imgs: [], lofi_prototype: 'The low-fidelity prototype connected the primary user flow of browsing a trailer and booking tickets. This consequently would enable usability study to be conducted on the prototype.', lofi_prototype_img: require('@/assets/images/lofi_prototype.png'), usability_study: 'A usability study was conducted on potential users and the main findings uncovered during the study are as follows:', usability_study_fidings: [{ id: 1, title: 'Multiple viewing time', data: 'Users want to be able to select from a wide range of viewing time.'}, { id: 2, title: 'Navigation', data: 'Users find it difficult locating their account information.'}, { id: 3, title: 'More payment options', data: 'Users want more payment options.'}] },
                refining_the_design: { before_after: [{id: 1, description: 'The initial design only allow the user to select the day in which they would like to visit the theater. So, after the usability study I added the ability to choose from multiple time within a particular day.', img: require('@/assets/images/before_after.png')}, { id: 2, description: 'The second usability study revealed users were finding issues with the initial navigation. I introduced a bottom-placed navigation system as well as in-app streaming option.', img: require('@/assets/images/before_after.png')}], accessibility_considerations: [{id: 1, title: 'Close-captioning', description: 'I provided close-caption controls for all movies for users with hearing impaired. This would enable them to follow through all movies.'}, { id: 2, title: 'Icons', description: 'I used icons to help improve navigation throughout the app'}], hifi: 'The final fidelity mockups are as follows;', refined_designs: [require('@/assets/images/flexsale-refined-1.png'), require('@/assets/images/flexsale-refined-2.png'), require('@/assets/images/flexsale-refined-3.png'), require('@/assets/images/flexsale-refined-4.png'), require('@/assets/images/flexsale-refined-5.png'), require('@/assets/images/flexsale-refined-6.png')], screen_variations: '', screen_variations_imgs: [], hifi_prototype: 'The final high-fidelity prototype ensures a smooth user flow for viewing and booking of movie trailers. It also delivers an intuitive navigation that meet users needs.', hifi_prototype_video: 'https://www.youtube.com/embed/A5idbGOWRgk?loop=1', video_title: 'Flexsale prototype'},
                going_forward: { takeaways: [{id: 1, title: 'Impact', p1: 'The app puts Infinity Theater on the map as the go to app for users who want to enjoy good movies either in theater or on-demand.', p2: 'One quote from peer feedback:', p3: '“Finally, I can quickly watch trailers of upcoming movies and book my tickets. This would definitely be my go-to app”'}, {id: 2, title: 'What I learned', p1: 'In designing the app, I found out that my initial ideas about what I thought users needed were totally in contrast to what they really need. Usability studies and peer feedback helped greatly in iterating on the initial design and crafting a better user experience.', p2: '', p3: ''},], nextstep: [{id: 1, title: 'Testing', description: 'Conduct another round of usability studies to validate whether the pain points users experienced have been effectively addressed. Also, to ascertain if the in-app streaming feature is well optimized.'}, {id: 2, title: 'User research', description: 'Conduct more user research to determine any new areas of need.'},]}
            },
            { id: 3, color: '#F2BE5B', color2: '#3C74EB', type: 'case study', title: 'Phoenix Career Mentorship App', thumbnail: require('@/assets/images/project-3-thumbnail.png'), banner: require('@/assets/images/project-3-banner.png'), banner_2: '', description: 'Designing for social good: An app to help formarly incarcerated individuals to find jobs.',
                overview: { problem: 'd', product: 'Flexsale is a multi-platform inventory and point of sale application that provide retail store owners a flexible way to manage their store inventory, record sales, perform sales analysis, get notified of expiring products.', goal: '', role: '', responsibilities: '', duration: ''},
                empathize: { overview: '', pain_points: [ { id: 1, title: 'Lorem', description: 'Lorem ipsum', title2: '', opportunity: ''} ], person_name: '', problem_statement: '', persona_img: '', age: '', education: '', hometown: '', family: '', ocupation: '', headline: '', goals: [], frustrations: [], scenario: '', competitive_audit: '', audit_img: '', ideation: '', ideation_img: '', user_journey_map: '', user_journey_map_img: ''},
                starting_the_design: { site_map: '', site_map_img: '', paper_wireframe: '', paper_wireframe_img: '', digital_wireframe: '', digital_wireframe_img: '', screen_variations: '', screen_variations_imgs: [], lofi_prototyp: '', lofi_prototype_img: '', usability_study: '', usability_study_fidings: [] },
                refining_the_design: { before_after: [], accessibility_considerations: [], refined_designs: [], screen_variations: '', screen_variations_imgs: [], hifi_prototype: '', hifi_prototype_video: '', video_title: ''},
                going_forward: { takeaways: [], nextstep: []}
            },
            { id: 4, color: '#51D6D6', color2: '#3C74EB', type: 'case study', title: 'Pixels Tutorials App', thumbnail: require('@/assets/images/project-4-thumbnail.png'), banner: require('@/assets/images/project-4-banner.png'), banner_2: '', description: 'An app to help users find design tutorials and learn new skills.',
                overview: { problem: 'd', product: 'Flexsale is a multi-platform inventory and point of sale application that provide retail store owners a flexible way to manage their store inventory, record sales, perform sales analysis, get notified of expiring products.', goal: '', role: '', responsibilities: '', duration: ''},
                empathize: { overview: '', pain_points: [ { id: 1, title: 'Lorem', description: 'Lorem ipsum', title2: '', opportunity: ''} ], person_name: '', problem_statement: '', persona_img: '', age: '', education: '', hometown: '', family: '', ocupation: '', headline: '', goals: [], frustrations: [], scenario: '', competitive_audit: '', audit_img: '', ideation: '', ideation_img: '', user_journey_map: '', user_journey_map_img: ''},
                starting_the_design: { site_map: '', site_map_img: '', paper_wireframe: '', paper_wireframe_img: '', digital_wireframe: '', digital_wireframe_img: '', screen_variations: '', screen_variations_imgs: [], lofi_prototyp: '', lofi_prototype_img: '', usability_study: '', usability_study_fidings: [] },
                refining_the_design: { before_after: [], accessibility_considerations: [], refined_designs: [], screen_variations: '', screen_variations_imgs: [], hifi_prototype: '', hifi_prototype_video: '', video_title: ''},
                going_forward: { takeaways: [], nextstep: []}
            }
        ]
    },
    mutations: {
        closeProject(state) {
            document.body.classList.remove('fixed-body')
            state.project.active = false
            state.project.project = {}
        },
        showProject(state, payload) {
            // document.body.classList.add('fixed-body')
            const thisProject = state.projects.find(p => p.id == payload)
            state.project.project = thisProject
            window.scrollTo(0,0)
            // setTimeout(()=> {
            //   state.project.active = true
            // }, 5)
        },
        findIndex(state, payload) {
            const prod = state.projects[payload]
            state.project.project = prod
        },
        showNext(state) {
            const length = state.projects.length -1
            const id = state.project.project.id
            const i = state.projects.findIndex(x => x.id === id)
            if(i < length) {
              this.commit('findIndex', i+1)
            }else {
              this.commit('findIndex', 0)
            }
      
        },
        showPrevious(state) {
            const length = state.projects.length
            const id = state.project.project.id
            const i = state.projects.findIndex(x => x.id === id)
            if(i > 0) {
              this.commit('findIndex', i-1)
            }else {
              this.commit('findIndex', length-1)
            }
        },
    },
    getters: {
        getProject: (state) => state.project,
        getProjects: (state) => state.projects,
        getIntro: (state) => state.intro
    },
}